---

- name: Set the IP address of the Swarm manager as a fact
  set_fact:
    managerip: "{{ item }}"
  delegate_to: localhost
  with_items:
    - "{{ groups['manager'] }}"

- debug:
    msg: "Complete, you can connect to your manager using ssh root@{{ managerip }}, your worker IP addresses are {{ groups['workers'] }}"
  delegate_to: localhost